SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
    FROM ANIMAL_INS INS JOIN ANIMAL_OUTS OUTS
        ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.SEX_UPON_INTAKE LIKE '%INTACT%'
    AND (OUTS.SEX_UPON_OUTCOME LIKE '%SPAYED%'
        OR OUTS.SEX_UPON_OUTCOME LIKE '%NEUTERED%')