SELECT a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
FROM ANIMAL_INS a JOIN ANIMAL_OUTS b
ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE SUBSTR(SEX_UPON_INTAKE, 0, 6) = 'Intact' AND 
(
    SUBSTR(SEX_UPON_OUTCOME, 0, 8) = 'Neutered'
    OR SUBSTR(SEX_UPON_OUTCOME, 0, 6) = 'Spayed'
);